language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: s3
  access_key_id: AKIAIJB4NTUZLR27636Q
  secret_access_key:
    secure: "cfD7FU7cJnYDfvD5PgxVvH71D62ic7+aZh/E0r3/UXJV1jPsySXu+6bMsjKh8jhNH7BKESRixn7PnHMpP3l3jNsdTuZ2bzGP65xkYap6kW4UZh0Ki6VepXFWgOObum7HtB8B3+oJ8MvtImZKWsa1I7x1GBxeZq6xgI4xHv20+W+hPDflGzHZTxiY2froAjRKexL2vAmOfiBdtZMhjXdfzDhP+os3Tlibcf8aYH3YONwAL+0ygyFhskEWi46Wv2rYyaJpqOznictLIgQ9COYFiEl+9r4W2U+CvCzK/D1k4jfNHMTXjH34NqIKI0KUnJXkP4yrBd2NBNZPWQuZKcxm9ujbd3d4QG1f7J2sByKQIL3i37tKmhNzWZ1vsuxeZP6FDeDKBvEIr9umgVIil8eYGMhBPjedt3AOYjehwTNEgwk8ywkb41wQZCW5bsRI7IwkqIcqfWUGpyTGjDsiggZJ0wmd3U1IVeT1vUcmKDIBNd7i6s65Bhbgj9Hl3f98/y0SmXbj9uHvpcGrshJwwZ+6DwXrrp2CNjUj4mYQUTqcK5YHHGAa8PaGOHDKLzNX0ewKWyg4ynjXzcDu+SyJie4kwNZ9s1i3JNRrzNLQ25qGb6y7G/cKcF5S+C/UNRWzlSCIob54ZiZrnaHiTj74myoqN7wX6dtPdJz68FYyzGjPnyI="
  bucket:
    secure: "cVhh25ZfuI6DcaY/grBQAGdGBJs2Zf2YMRjbWuXq5F8LJ//fDt3vdfbmZNwUwwVxLrIzLkhwmN+y2jg5fnPDttealses/UN54jDQOAwrmnhbS1LOZOKhmHZX5TrWvQ8NtNzsPdbk4NvHjmOnyjSE5QLnwb0AsXnPL8XjJZJRiKITmo5Zs6MxJC18McCXS7+jIvE0ILvFqLAqJ95fDe+q48ZmCS94RgolCr7kD1eRGqpOB4uQus7xwKbxK5IIYdks6JIzrCmKT3u5Qo/fyNT/Q/1Xa7ZFmmVPnExw4P7RvNm5M70YJ/2SrmINVZbTwW24/aRVFBltky4PBbe8jzf8mbgRdlaaHSyP8fDnUFJGEgJV20Trl3L47S5dJDYq9WuDlZWwEqTf3KZZq9zb41Z5fmaE8SZ22wIhioydhzVIJ6jQ73fiaXTOKI6HUnooVW1+EAqpiwkqh8XpFSZv6J2cStxOWPTVY/UM4Shva4lNsCfbLcFwy7orOx1tOszMyvh5NndJUSobCufkKicEzaVuRhqktE3JgONDlDK19E+sBSru+ap/mdOmtXs9Y6WnXkEg8Bs0O0gPAmtBU79DhwK67VXGuclZfpbcpKviV6wHID6Iq2VmahvqnNKfkyz1uF5662SYEtF5amoTXRvu7kqZXxi76k52A7fAM7a5o5g9p7A="
  local-dir: build
  acl: public_read
  skip_cleanup: true
env:
  global:
    secure: oYv2asaNCVnw/os4SwXmhOiIeGc5LJntlXef+stZlydfyRrNFpWtKyVz5Je6L2w3QbvvVhQEXvzRym2mAeokaYEq7cjWPwqCo9Kus5nIHtM8p9SB7mY2ESUbcab/7fq+VbnSfySYDCzoixglHkpeumK1EkLq0SOfZV30pAQSUa+FA459BqJoXP9uc9RQVeKXin3fzV7oKUfLGaILsWMkoBpziIY+3c3KWuwnEUywnzIFtR9jRQfIybkYDqzMzQwZ444WnahiR5xbRKFLa1LPyyKeDN/OpOnFROQMCNQsnNS22BXGYtjHd21eetEPlZCT/dGZI7Qpd61xSaYTtZfXrKh9JylawjwuE4ZyAfgHOWICw+emvS1dEiSP9znrQ3ossnpZxeZg3kRxwPZgciKab5qLOTH25DYNllnyF/IDBhTO4f3ouhDulvkZBcVPonFFDN8kEsVDrNNsoe2Uqi0h4K2FIFcBVbvHQoJnHBBW7+t4QZl36yljBxTxUpPamosEjztOscwzKAK8fVV8II4VHUwtPD0Ka8Lg98rAXM+IaIctDnV1AXKh+To10ZYa/8FsuU+MX2bcMeSe/VMxGlvEEgJ6vq0sZz0NNPN/RT6aH0Lwwxs1iCwVIhuAY9Vanzp4S1GGGUdi+0/YCGPP1fJEnKttTMYb7CbMaNPw4/1kArQ=
