language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: s3
  access_key_id: AKIAIJB4NTUZLR27636Q
  secret_access_key:
    secure: Wv25OlzVKbCfuAZaVKhIXABTt6Jg+nmX/576jHKk8P+NaKGUPRoTvhHYQdmyuvhv661kA9N025tRB+31mxUFPXWhbem3wrTh+zHyDaqaj730vxTmEe5QcZCqQ5WZrLeDs4IzNRb6iDBjamcsB2A8jMtetNmP+xAI8A6LgCDSsGuyPbgbD/MDvQ1GCJNxV8WM+SNQ7ZNo5wNXLBItBVNPJb/teLMDiFR9Q/qO3JT275ekN8+YKeOlpo5wr6jETiUJuHfiiHcCRn6PZd+W0DYTFuqNaVjcHZaq/gvWbTeeIYSQMKxLPkwxBGBtgQP2iAJRt1EVP0z6GYjH6wW8G00Bm2M6pDnwzBIZuKCuX0azLud/KjFngf1jCgtIQvUk7Z7L1D9neTvTYDbUdQcUwE7WPBh/qI4GGGjpt3FeVyieX80gWmChW92PksjSKMQR0qvUQWqsMXEBB4iIrf4SwEe/vreeSKZJBFo81v3pY+L4OHPgoapciEFBm3ysNrXlx0t8aO6fKiY19lprCnOERYLFxn1et3mA94UCSaP/rmq9WA7Iv4k0p5S//cqcGhICHIiBPzSRMOVA7ZBUZ0r7jrDnc6Dv917oP2TPtSv7jXNjBoMg3v6Y75YpuN9Uf3pMGVCZoWPX8lBV777HNkpPRLCSXDV/emWqFWGqQ4AhsLqJa4M=
  bucket:
    secure: "aBca7O6grKOnmujfpnIrm8gbf1KvEtb1sYJe7hz/6nYDz6kfTFqKLXxmlomkBFuB1XmGjGIrQE+VhchIWPhwzj/DwZsZEv4w2hO9vhxfITgVQVDKU3M46X/+lccbZT3xNZn8dKSXEBiitDtHbWNFhxvpNy8w2aWmMmXry/qJ0pKzG1WE45UdDg5exm7FGVoIT4kIT8bVp2ClsUxHiwIM5Bv3jho1eLA9fAjTVncZVqoqMUwsxHdO9oWUmAU2iqUvW+oe3u9JmKeXmeVXVUX6k+TZLTkbP3bjm3UzDUbd0zAUFy9/7C0n1CTSdewEu+nCFtImpcRe7yb/o4hY4bH7LjXYSQRBlegzFX+F73Etp69+9zLbV9KVZaDro/6GoiMmiFMAWm4Jv0+8rSeMWrJlCno3dZf8D4sSAgClI93G4C4ZzsQgppxQLxUl+x/G1V0Optwgq+gxztFCsFgZHyDX14aHAwBo1/AzUN2GiD0qzmVKPmEtmtRmjO2euNbm3im1S27XXF7VK3z+Kj0ZDjsS+Lq2PAMUshtyGVLfWrfkncBMdyAMc0HJ9gPaurzq/3w8tW7L6SFlHUvX4pG5Vffs2d5xkaM4dTiYS4Ss9jgIPqDq+qrPqSRMGAHBGzikFM0up7+0ns7xivNFPrhH+d9Ir0aSxRIX/uW3E4SRfOShBeQ="
  local-dir: build
  acl: public_read
  skip_cleanup: true
env:
  global:
    secure: oYv2asaNCVnw/os4SwXmhOiIeGc5LJntlXef+stZlydfyRrNFpWtKyVz5Je6L2w3QbvvVhQEXvzRym2mAeokaYEq7cjWPwqCo9Kus5nIHtM8p9SB7mY2ESUbcab/7fq+VbnSfySYDCzoixglHkpeumK1EkLq0SOfZV30pAQSUa+FA459BqJoXP9uc9RQVeKXin3fzV7oKUfLGaILsWMkoBpziIY+3c3KWuwnEUywnzIFtR9jRQfIybkYDqzMzQwZ444WnahiR5xbRKFLa1LPyyKeDN/OpOnFROQMCNQsnNS22BXGYtjHd21eetEPlZCT/dGZI7Qpd61xSaYTtZfXrKh9JylawjwuE4ZyAfgHOWICw+emvS1dEiSP9znrQ3ossnpZxeZg3kRxwPZgciKab5qLOTH25DYNllnyF/IDBhTO4f3ouhDulvkZBcVPonFFDN8kEsVDrNNsoe2Uqi0h4K2FIFcBVbvHQoJnHBBW7+t4QZl36yljBxTxUpPamosEjztOscwzKAK8fVV8II4VHUwtPD0Ka8Lg98rAXM+IaIctDnV1AXKh+To10ZYa/8FsuU+MX2bcMeSe/VMxGlvEEgJ6vq0sZz0NNPN/RT6aH0Lwwxs1iCwVIhuAY9Vanzp4S1GGGUdi+0/YCGPP1fJEnKttTMYb7CbMaNPw4/1kArQ=
